// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/mrnaghibi/wallet/controller"
	"github.com/mrnaghibi/wallet/repository"
	"github.com/mrnaghibi/wallet/service"
)

// Injectors from wire.go:

func initWalletController() controller.WalletController {
	walletRepository := repository.WalletRepositoryProvider()
	walletService := service.WalletServiceProvider(walletRepository)
	walletController := controller.WalletControllerProvider(walletService)
	return walletController
}
